cloud_server_ip: "spacis-cloud.ddns.net"
cloud_server_port: 8765
sound_station_lla: [41.178253, -8.594974, 150]
balloon_target_lla: [41.177228, -8.599973, 150]
manual_port_config: false
manual_serial_port: "COM8"
